// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0wIzyfETtGHMgL5_oRDpaCetyan5e_ok',
    appId: '1:257165992889:web:85fa7f254e44d667b14c68',
    messagingSenderId: '257165992889',
    projectId: 'uclass-ucss',
    authDomain: 'uclass-ucss.firebaseapp.com',
    storageBucket: 'uclass-ucss.firebasestorage.app',
    measurementId: 'G-XWLWXL5SER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKq5WkMIHB-8hmKwGWWNWbX_bWAGR3FLQ',
    appId: '1:257165992889:android:c5bd3bdf1db0c622b14c68',
    messagingSenderId: '257165992889',
    projectId: 'uclass-ucss',
    storageBucket: 'uclass-ucss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZTf_U-MCjlOCaNF_jqEdzUp70pZBZjqY',
    appId: '1:257165992889:ios:5d272f831ccc3d50b14c68',
    messagingSenderId: '257165992889',
    projectId: 'uclass-ucss',
    storageBucket: 'uclass-ucss.firebasestorage.app',
    iosBundleId: 'com.tareas.uclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0wIzyfETtGHMgL5_oRDpaCetyan5e_ok',
    appId: '1:257165992889:web:db725eccf25c7bfeb14c68',
    messagingSenderId: '257165992889',
    projectId: 'uclass-ucss',
    authDomain: 'uclass-ucss.firebaseapp.com',
    storageBucket: 'uclass-ucss.firebasestorage.app',
    measurementId: 'G-8NS1Z7HXRZ',
  );
}
